import type { Theme } from './schema';

/**
 * Tema por defecto: "maquinaria" (el sector activo del sitio actual).
 * Sirve como semilla de la tabla `themes` y como fallback si la API no responde.
 * TODOS los valores son editables desde el admin — esto es solo el punto de partida.
 */
export const defaultTheme: Theme = {
  slug: 'maquinaria',
  name: 'Maquinaria (default)',
  active: true,
  tokens: {
    colors: {
      light: {
        primary: '#B45309',
        primaryFg: '#FFFFFF',
        secondary: '#334155',
        accent: '#D97706',
        background: '#F8FAFC',
        surface: '#FFFFFF',
        text: '#0F172A',
        textMuted: '#64748B',
        border: '#E2E8F0',
        success: '#15803D',
        warning: '#A16207',
        error: '#B91C1C',
      },
      dark: {
        primary: '#F59E0B',
        primaryFg: '#1C1917',
        secondary: '#94A3B8',
        accent: '#FBBF24',
        background: '#0B1220',
        surface: '#111A2C',
        text: '#E2E8F0',
        textMuted: '#94A3B8',
        border: '#1E293B',
        success: '#4ADE80',
        warning: '#FACC15',
        error: '#F87171',
      },
    },
    typography: {
      fontSans: 'Inter',
      fontHeading: 'Inter',
      baseSizePx: 16,
      scaleRatio: 1.25,
    },
    shape: {
      radiusSm: '4px',
      radiusMd: '8px',
      radiusLg: '14px',
      buttonStyle: 'solid',
      buttonRadius: '8px',
    },
    sections: [
      { key: 'home.hero', enabled: true, order: 0 },
      { key: 'home.categories', enabled: true, order: 1 },
      { key: 'home.featured-products', enabled: true, order: 2 },
      { key: 'home.strategic-sectors', enabled: true, order: 3 },
      { key: 'home.why-choose-us', enabled: true, order: 4 },
      { key: 'home.services', enabled: true, order: 5 },
      { key: 'home.banners', enabled: true, order: 6 },
      { key: 'home.blog', enabled: true, order: 7 },
      { key: 'home.reviews', enabled: true, order: 8 },
      { key: 'home.faq', enabled: true, order: 9 },
    ],
    quoteMode: false,
  },
  copys: {
    es: {
      'site.name': 'ServMaq24',
      'site.tagline': 'Maquinaria y equipo industrial',
      'home.hero.title': 'Maquinaria y equipo para tu proyecto',
      'home.hero.subtitle': 'Venta y renta de maquinaria con cobertura nacional',
      'home.hero.cta': 'Ver catálogo',
      'product.cta.buy': 'Comprar ahora',
      'product.cta.addToCart': 'Añadir al carrito',
      'product.cta.quote': 'Solicitar cotización',
      'product.cta.inquiry': 'Solicitar información',
      'product.price.onQuote': 'Precio bajo cotización',
      'product.rental.badge': 'Disponible en renta',
      'product.outOfStock': 'Agotado',
      'product.category': 'Categoría',
      'product.medical.title': 'Información técnica',
      'product.medical.lote': 'Lote',
      'product.medical.caducidad': 'Fecha de caducidad',
      'product.medical.ficha': 'Descargar ficha técnica (PDF)',
      'product.medical.dc3': 'Certificación DC-3',
      'home.categories.title': 'Categorías',
      'home.featured.title': 'Productos destacados',
      'home.featured.viewAll': 'Ver todos los productos',
      'home.sectors.title': 'Sectores estratégicos',
      'home.whyChooseUs.title': '¿Por qué elegirnos?',
      'home.services.title': 'Nuestros servicios',
      'home.blog.title': 'Últimas noticias',
      'home.blog.readMore': 'Leer más',
      'home.reviews.title': 'Lo que dicen nuestros clientes',
      'home.faq.title': 'Preguntas frecuentes',
      'catalog.title': 'Catálogo de productos',
      'catalog.search.placeholder': 'Buscar productos…',
      'catalog.search.button': 'Buscar',
      'catalog.empty': 'No encontramos productos para tu búsqueda.',
      'pagination.prev': '← Anterior',
      'pagination.next': 'Siguiente →',
      'auth.login.title': 'Iniciar sesión',
      'auth.login.submit': 'Entrar',
      'auth.login.noAccount': '¿No tienes cuenta? Regístrate',
      'auth.register.title': 'Crear cuenta',
      'auth.register.submit': 'Registrarme',
      'auth.register.haveAccount': '¿Ya tienes cuenta? Inicia sesión',
      'auth.field.name': 'Nombre completo',
      'auth.field.email': 'Correo electrónico',
      'auth.field.password': 'Contraseña',
      'auth.logout': 'Salir',
      'auth.greeting': 'Hola',
      'cart.title': 'Tu carrito',
      'cart.empty': 'Tu carrito está vacío.',
      'cart.browse': 'Explorar productos',
      'cart.qty': 'Cantidad',
      'cart.remove': 'Quitar',
      'cart.total': 'Total',
      'cart.checkout': 'Proceder al pago',
      'cart.added': 'Añadido al carrito',
      'checkout.title': 'Finalizar compra',
      'checkout.contact.title': 'Datos de contacto y envío',
      'checkout.field.phone': 'Teléfono',
      'checkout.field.address': 'Dirección',
      'checkout.field.city': 'Ciudad',
      'checkout.field.zip': 'Código postal',
      'checkout.field.note': 'Notas del pedido (opcional)',
      'checkout.method.title': 'Método de pago',
      'checkout.summary.title': 'Resumen del pedido',
      'checkout.submit': 'Confirmar pedido',
      'checkout.loginRequired': 'Inicia sesión para completar tu compra',
      'order.title': 'Pedido',
      'order.thanks': '¡Gracias por tu pedido!',
      'order.number': 'Número de pedido',
      'order.status.pending': 'Pendiente',
      'order.paymentStatus': 'Estado del pago',
      'order.method': 'Método de pago',
      'order.instructions.title': 'Instrucciones de pago',
      'order.items.title': 'Productos',
      'quote.form.title': 'Solicitar cotización',
      'quote.form.subtitle': 'Cuéntanos qué necesitas y te enviaremos una cotización a la medida.',
      'quote.form.company': 'Empresa (opcional)',
      'quote.form.region': 'Región / Estado',
      'quote.form.industry': 'Industria',
      'quote.form.address': 'Dirección de entrega (para calcular flete)',
      'quote.form.comments': 'Comentarios adicionales',
      'quote.form.days': 'Días de renta',
      'quote.form.qty': 'Cantidad',
      'quote.form.submit': 'Enviar solicitud',
      'quote.form.success.title': '¡Solicitud recibida!',
      'quote.form.success.body': 'Nuestro equipo te contactará con tu cotización.',
      'quote.form.number': 'Número de cotización',
      'quote.status.pending': 'Pendiente',
      'quote.status.completed': 'Cotizada',
      'account.title': 'Mi cuenta',
      'account.profile.title': 'Mis datos',
      'account.profile.save': 'Guardar cambios',
      'account.profile.saved': 'Datos actualizados',
      'account.password.title': 'Cambiar contraseña',
      'account.password.current': 'Contraseña actual',
      'account.password.new': 'Contraseña nueva (mínimo 8 caracteres)',
      'account.password.submit': 'Actualizar contraseña',
      'account.password.changed': 'Contraseña actualizada',
      'account.wishlist.title': 'Mis favoritos',
      'account.wishlist.empty': 'Aún no tienes favoritos.',
      'wishlist.add': 'Guardar en favoritos',
      'wishlist.remove': 'Quitar de favoritos',
      'comments.title': 'Opiniones del producto',
      'comments.empty': 'Sé el primero en opinar.',
      'comments.form.title': 'Escribe tu opinión',
      'comments.form.rating': 'Calificación',
      'comments.form.text': 'Tu opinión',
      'comments.form.submit': 'Publicar opinión',
      'comments.loginToComment': 'Inicia sesión para opinar',
      'checkout.coupon.label': 'Cupón de descuento',
      'checkout.coupon.apply': 'Aplicar',
      'checkout.coupon.applied': 'Cupón aplicado',
      'checkout.coupon.invalid': 'El cupón no es válido o expiró',
      'checkout.discount': 'Descuento',
      'vendors.title': 'Nuestros vendedores',
      'vendors.empty': 'Aún no hay vendedores registrados.',
      'vendors.products': 'productos',
      'vendors.visit': 'Ver tienda',
      'vendor.store.title': 'Tienda',
      'vendor.panel.title': 'Panel de vendedor',
      'vendor.panel.balance': 'Saldo disponible',
      'vendor.panel.products': 'Mis productos',
      'vendor.panel.orders': 'Mis ventas',
      'vendor.panel.withdraws': 'Retiros',
      'vendor.apply.title': 'Conviértete en vendedor',
      'vendor.apply.subtitle': 'Envía tu solicitud y nuestro equipo la revisará.',
      'vendor.apply.shopName': 'Nombre de la tienda',
      'vendor.apply.shopNumber': 'Teléfono de la tienda',
      'vendor.apply.shopAddress': 'Dirección de la tienda',
      'vendor.apply.regNumber': 'RFC / Registro',
      'vendor.apply.message': 'Cuéntanos de tu negocio',
      'vendor.apply.submit': 'Enviar solicitud',
      'vendor.apply.pending': 'Tu solicitud está en revisión. Te avisaremos cuando sea aprobada.',
      'vendor.products.new': 'Nuevo producto',
      'vendor.products.name': 'Nombre del producto',
      'vendor.products.category': 'Categoría',
      'vendor.products.price': 'Precio',
      'vendor.products.oldPrice': 'Precio anterior (tachado)',
      'vendor.products.stock': 'Existencias',
      'vendor.products.brand': 'Marca',
      'vendor.products.description': 'Descripción',
      'vendor.products.photo': 'Foto del producto',
      'vendor.products.isRental': 'Disponible en renta',
      'vendor.products.rentalFreight': 'Tarifa de flete por km (renta)',
      'vendor.products.create': 'Publicar producto',
      'vendor.products.created': 'Producto publicado',
      'vendor.products.deactivate': 'Desactivar',
      'vendor.products.empty': 'Aún no tienes productos.',
      'vendor.orders.empty': 'Aún no tienes ventas.',
      'vendor.withdraws.request': 'Solicitar retiro',
      'vendor.withdraws.amount': 'Monto',
      'vendor.withdraws.method': 'Método (transferencia, PayPal…)',
      'vendor.withdraws.reference': 'Referencia / datos de cuenta',
      'vendor.withdraws.submit': 'Solicitar',
      'vendor.withdraws.empty': 'No tienes retiros registrados.',
      'about.mision': 'Misión',
      'about.vision': 'Visión',
      'about.objetivos': 'Objetivos',
      'contact.title': 'Contacto',
      'contact.subtitle': 'Estamos para ayudarte. Escríbenos o llámanos.',
      'contact.email': 'Correo',
      'contact.phone': 'Teléfono',
      'contact.address': 'Dirección',
      'newsletter.title': 'Recibe nuestras novedades',
      'newsletter.placeholder': 'Tu correo electrónico',
      'newsletter.submit': 'Suscribirme',
      'newsletter.success': '¡Listo! Te avisaremos de las novedades.',
      'newsletter.error': 'No pudimos registrar tu correo.',
      'nav.about': 'Quiénes somos',
      'nav.vendors': 'Vendedores',
      'track.title': 'Rastrear pedido',
      'track.subtitle': 'Ingresa tu número de pedido y el correo con el que compraste.',
      'track.field.number': 'Número de pedido',
      'track.submit': 'Rastrear',
      'track.notFound': 'No encontramos un pedido con esos datos.',
      'track.entries.title': 'Historial de envío',
      'track.noEntries': 'Tu pedido aún no tiene eventos de envío.',
      'nav.track': 'Rastrear pedido',
      'account.quotes.title': 'Mis cotizaciones',
      'account.quotes.empty': 'Aún no tienes cotizaciones.',
      'account.orders.title': 'Mis pedidos',
      'account.orders.empty': 'Aún no tienes pedidos.',
      'account.orders.view': 'Ver detalle',
      'nav.myOrders': 'Mis pedidos',
      'nav.cart': 'Carrito',
      'nav.login': 'Iniciar sesión',
      'nav.home': 'Inicio',
      'nav.products': 'Productos',
      'nav.categories': 'Categorías',
      'nav.blog': 'Blog',
      'nav.contact': 'Contacto',
      'footer.rights': 'Todos los derechos reservados',
    },
  },
};
